### ISSUE TITLE
Remove dependency on extensible-records coq package

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/saw-core-coq#9]
@eddywestbrook recently changed the translation of saw-core records to avoid using this particular coq package. We should remove remaining dependencies on the library from other hand-written coq files so that we won't need the extensible-records package for anything. The (unmaintained) extensible-records library doesn't work with the latest version of coq, so removing the dependency will let us use the latest version.

**Comment by eddywestbrook** [comment]
This was done last week. Sorry, I didn't see this issue until now.
